trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'browserstack'
- script: |
    echo Starting the build
    mvn clean
    mvn compile
    mvn test -P single
  displayName: 'Build with Maven'
- task: BrowserStackResults@0